### ISSUE TITLE
Extension deletes any saves on settings.json or other files

### ISSUE THREAD

**Issue by vbasky** [Reduxx/vscode-php-sort-imports#2]
With this extension installed if I were to save any non php file, the entire contents gets vanished for eg: todo files or settings.json. I want this extension not to affect other types of files

**Comment by dmyers** [comment]
I had this happen too on multiple files even .gitignore and wrote a replication guide in #3. I wasted a number of hours tracking this down and was a huge headache.  🤕 

Were you able to continue using this extension or did you just disable or uninstall it?

**Comment by vbasky** [comment]
I closed the issue because it wasn't acknowledged as an existing issue. I had to uninstall the extension
