### ISSUE TITLE
Running for all languages - clearing out whole file on save

### ISSUE THREAD

**Issue by dmyers** [Reduxx/vscode-php-sort-imports#3]
I recently installed this extension and spent a considerable amount of time tracking down which extension was clearing out my files on save intermittently and traced it down to this one.

I noticed that it should just be running for the `PHP` language in the package.json, but what seems to have happened in my case is I first open a non-php file such as .gitignore, then open a .php file, and return back to the .gitignore, make a change and save the file, and it is immediately truncated and the changes are persisted to disk and I can't restore the contents at all. I replicated this with my settings.json file too and a few other files and ultimately had to just disable this extension, but I liked the idea of it a lot.

Have you seen this before?

**Comment by dmyers** [comment]
Upon looking through issues, this seems to be the same thing reported in #2 which was oddly deleted by the original user without update.

**Comment by riverrun46** [comment]
I encountered the same issue. Felt flustrated to locate the problem. It just truncated my settings.json / keybindings.json while I don't have any backups. (￣◇￣;)
